version: "3.9"

services:
  api-censo-fundeb:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-censo-fundeb.rule=Host(`api.saberes.cloud`)"
      - "traefik.http.routers.api-censo-fundeb.entrypoints=web"
      - "traefik.http.services.api-censo-fundeb.loadbalancer.server.port=8000"
    restart: unless-stopped
