services:
  api-censo-fundeb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-censo-fundeb
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
